export const LOCAL_DB_NAME = 'niger_hmis_outreach.db';

export const CREATE_TABLES_SQL = [
  `CREATE TABLE IF NOT EXISTS lgas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    device_id TEXT,
    user_id TEXT,
    created_offline_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE TABLE IF NOT EXISTS wards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    lga_uuid TEXT NOT NULL REFERENCES lgas(uuid) ON UPDATE CASCADE ON DELETE CASCADE,
    name TEXT NOT NULL,
    device_id TEXT,
    user_id TEXT,
    created_offline_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(lga_uuid, name)
  );`,
  `CREATE TABLE IF NOT EXISTS patients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    server_id INTEGER,
    device_id TEXT,
    user_id TEXT,
    created_offline_at TEXT,
    full_name TEXT,
    first_name TEXT,
    middle_name TEXT,
    last_name TEXT,
    is_anonymized INTEGER NOT NULL DEFAULT 0,
    age_years INTEGER CHECK(age_years IS NULL OR (age_years BETWEEN 0 AND 120)),
    is_estimated_age INTEGER NOT NULL DEFAULT 0,
    sex TEXT,
    phone TEXT,
    nhis_status TEXT,
    nin TEXT,
    lga_uuid TEXT REFERENCES lgas(uuid) ON UPDATE CASCADE ON DELETE SET NULL,
    ward_uuid TEXT REFERENCES wards(uuid) ON UPDATE CASCADE ON DELETE SET NULL,
    primary_facility_uuid TEXT,
    consent_confirmed INTEGER NOT NULL DEFAULT 0,
    temporary_id_hash TEXT,
    sync_status TEXT NOT NULL DEFAULT 'draft' CHECK(sync_status IN ('draft', 'pending', 'syncing', 'synced', 'failed', 'conflict')),
    synced_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    CHECK((is_anonymized = 1 AND full_name IS NULL) OR (is_anonymized = 0 AND full_name IS NOT NULL))
  );`,
  `CREATE TABLE IF NOT EXISTS encounters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    server_id INTEGER,
    patient_uuid TEXT NOT NULL REFERENCES patients(uuid) ON UPDATE CASCADE ON DELETE CASCADE,
    version_stamp INTEGER NOT NULL DEFAULT 1,
    encounter_date TEXT,
    outreach_location TEXT,
    presenting_complaint TEXT,
    symptoms_json TEXT,
    disease_program_category TEXT,
    preliminary_diagnosis TEXT,
    notes TEXT,
    services_provided_json TEXT,
    drugs_commodities_json TEXT,
    health_education_json TEXT,
    service_notes TEXT,
    outcome_status TEXT,
    referral_required INTEGER NOT NULL DEFAULT 0,
    referral_uuid TEXT,
    referral_facility TEXT,
    referral_reason TEXT,
    urgency_level TEXT,
    follow_up_date TEXT,
    referral_notes TEXT,
    device_id TEXT,
    user_id TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'draft' CHECK(sync_status IN ('draft', 'pending', 'syncing', 'synced', 'failed', 'conflict')),
    synced_at TEXT,
    current_step INTEGER NOT NULL DEFAULT 1,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE TABLE IF NOT EXISTS referrals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    server_id INTEGER,
    patient_uuid TEXT NOT NULL REFERENCES patients(uuid) ON UPDATE CASCADE ON DELETE CASCADE,
    encounter_uuid TEXT NOT NULL REFERENCES encounters(uuid) ON UPDATE CASCADE ON DELETE CASCADE,
    referral_facility TEXT,
    referral_reason TEXT NOT NULL,
    urgency_level TEXT NOT NULL,
    follow_up_date TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    device_id TEXT,
    user_id TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'draft' CHECK(sync_status IN ('draft', 'pending', 'syncing', 'synced', 'failed', 'conflict')),
    synced_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE TABLE IF NOT EXISTS sync_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,
    entity_uuid TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    device_id TEXT,
    user_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'syncing', 'synced', 'failed', 'conflict')),
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TEXT,
    last_error TEXT,
    backend_response_json TEXT,
    synced_at TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(entity_type, entity_uuid)
  );`,
  `CREATE TABLE IF NOT EXISTS sync_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    queue_id INTEGER,
    entity_type TEXT NOT NULL,
    entity_uuid TEXT NOT NULL,
    action TEXT NOT NULL,
    status TEXT NOT NULL,
    request_json TEXT,
    response_json TEXT,
    error_message TEXT,
    device_id TEXT,
    user_id TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE TABLE IF NOT EXISTS facilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    facility_type TEXT,
    lga_uuid TEXT REFERENCES lgas(uuid) ON UPDATE CASCADE ON DELETE SET NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE INDEX IF NOT EXISTS idx_facilities_lga ON facilities(lga_uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_patients_uuid ON patients(uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_patients_sync_status ON patients(sync_status);`,
  `CREATE INDEX IF NOT EXISTS idx_patients_created_at ON patients(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_encounters_uuid ON encounters(uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_encounters_patient_uuid ON encounters(patient_uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_encounters_sync_status ON encounters(sync_status);`,
  `CREATE INDEX IF NOT EXISTS idx_encounters_created_at ON encounters(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_referrals_uuid ON referrals(uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_referrals_encounter_uuid ON referrals(encounter_uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_referrals_sync_status ON referrals(sync_status);`,
  `CREATE INDEX IF NOT EXISTS idx_referrals_created_at ON referrals(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_sync_queue_uuid ON sync_queue(entity_type, entity_uuid);`,
  `CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status);`,
  `CREATE INDEX IF NOT EXISTS idx_sync_queue_created_at ON sync_queue(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_sync_logs_created_at ON sync_logs(created_at);`,
];

/**
 * Run these after CREATE_TABLES_SQL. Each is idempotent (uses IF NOT EXISTS semantics where possible).
 * For ADD COLUMN, SQLite will error if the column already exists — callers must catch and ignore SQLITE_ERROR.
 */
export const SCHEMA_MIGRATIONS_SQL = [
  `ALTER TABLE patients ADD COLUMN primary_facility_uuid TEXT`,
  `ALTER TABLE patients ADD COLUMN nin TEXT`,
];

export const NIGER_LGAS = [
  'Agaie', 'Agwara', 'Bida', 'Borgu', 'Bosso', 'Chanchaga', 'Edati', 'Gbako', 'Gurara',
  'Katcha', 'Kontagora', 'Lapai', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Muya',
  'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tafa', 'Wushishi',
];
